version: "3"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
      
  hub:
    image: selenium/hub
    ports:
      - '4444:4444'
  firefox:
    image: selenium/node-firefox:3.14.0-gallium
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    depends_on:
      - hub

volumes:
  db-data:
    external: false